# Generated by Django 5.1.3 on 2024-12-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_dadosloja_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ativacao', models.CharField(max_length=16)),
                ('tipo_certificado', models.IntegerField(choices=[(1, 'A1'), (2, 'A3')])),
                ('numero_caixa', models.CharField(max_length=3)),
                ('teste', models.BooleanField(default=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.dadosloja')),
            ],
        ),
    ]
