# Generated by Django 5.1.3 on 2024-12-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_nfe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosat',
            name='caminho',
            field=models.FilePathField(blank=True, null=True, recursive=True),
        ),
    ]
