# Generated by Django 5.1.3 on 2024-12-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_nfe', '0002_configuracaosat_caminho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosat',
            name='caminho',
        ),
    ]
