# Generated by Django 5.1.3 on 2024-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_nfe', '0003_remove_configuracaosat_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosat',
            name='caminho',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
