# Generated by Django 5.1.3 on 2024-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_nfe', '0004_configuracaosat_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosat',
            name='numero_sat',
            field=models.CharField(default='1234567891234567', max_length=16),
            preserve_default=False,
        ),
    ]
