# Generated by Django 5.1.3 on 2024-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos')),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('cfop', models.CharField(choices=[('1102', 'Compra para comercialização'), ('2102', 'Compra para comercialização - Interestadual'), ('1401', 'Devolução de venda de produção do estabelecimento'), ('2401', 'Devolução de venda de produção do estabelecimento - Interestadual'), ('1403', 'Devolução de venda de mercadoria adquirida de terceiros'), ('2403', 'Devolução de venda de mercadoria adquirida de terceiros - Interestadual'), ('1556', 'Compra de bem para o ativo imobilizado'), ('2556', 'Compra de bem para o ativo imobilizado - Interestadual'), ('1949', 'Outras entradas'), ('2949', 'Outras entradas - Interestadual'), ('5102', 'Venda de mercadoria adquirida ou recebida de terceiros'), ('6102', 'Venda de mercadoria adquirida ou recebida de terceiros - Interestadual'), ('5403', 'Venda de mercadoria adquirida para não contribuinte'), ('6403', 'Venda de mercadoria adquirida para não contribuinte - Interestadual'), ('5405', 'Venda de mercadoria adquirida para a Zona Franca de Manaus ou Áreas de Livre Comércio'), ('6405', 'Venda de mercadoria adquirida para a Zona Franca de Manaus ou Áreas de Livre Comércio - Interestadual'), ('5949', 'Outras saídas'), ('6949', 'Outras saídas - Interestadual')], max_length=4)),
                ('cst', models.CharField(blank=True, choices=[('00', 'Tributada integralmente'), ('10', 'Tributada e com cobrança do ICMS por substituição tributária'), ('20', 'Com redução de base de cálculo'), ('30', 'Isenta ou não tributada e com cobrança do ICMS por substituição tributária'), ('40', 'Isenta'), ('41', 'Não tributada'), ('50', 'Suspensão'), ('51', 'Diferimento'), ('60', 'ICMS cobrado anteriormente por substituição tributária'), ('70', 'Com redução de base de cálculo e cobrança do ICMS por substituição tributária'), ('90', 'Outras')], max_length=2, null=True)),
                ('csosn', models.CharField(blank=True, choices=[('101', 'Tributada pelo Simples Nacional com permissão de crédito'), ('102', 'Tributada pelo Simples Nacional sem permissão de crédito'), ('103', 'Isenção do ICMS no Simples Nacional para faixa de receita bruta'), ('201', 'Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por substituição tributária'), ('202', 'Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária'), ('203', 'Isenção do ICMS no Simples Nacional para faixa de receita bruta e com cobrança do ICMS por substituição tributária'), ('300', 'Imune'), ('400', 'Não tributada pelo Simples Nacional'), ('500', 'ICMS cobrado anteriormente por substituição tributária ou antecipação'), ('900', 'Outros')], max_length=3, null=True)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('M²', 'Metro Quadrado'), ('CX', 'Caixa'), ('FD', 'Fardo'), ('ROLO', 'Rolo'), ('PAR', 'Par')], max_length=4)),
                ('ncm', models.CharField(max_length=8)),
                ('icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
