# Generated by Django 5.1.3 on 2024-11-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='fone',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='fone',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='numero',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cliente_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cliente_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
