# Generated by Django 5.1.3 on 2024-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosloja',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
