# Generated by Django 5.1.3 on 2024-12-02 20:38

import django.db.models.deletion
import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_remove_pessoajuridica_cliente_ptr_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(default=vendas.models.get_default_cliente, on_delete=django.db.models.deletion.SET_DEFAULT, to='clientes.cliente')),
            ],
        ),
    ]
