# Generated by Django 5.1.3 on 2024-12-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvenda',
            old_name='preco_unitario',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='desconto',
        ),
    ]
