# Generated by Django 5.1.3 on 2024-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_preco_unitario_itemvenda_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('01', 'Dinheiro'), ('02', 'Cartão de Crédito'), ('03', 'Cartão de Débito')], default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='venda',
            name='sat_gerado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='xml_gerado',
            field=models.BooleanField(default=False),
        ),
    ]
