# Generated by Django 5.1.3 on 2024-12-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_metodo_pagamento_venda_sat_gerado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('01', 'Dinheiro'), ('02', 'Cartão de Crédito'), ('03', 'Cartão de Débito')], max_length=2, null=True),
        ),
    ]
