# Generated by Django 5.1.3 on 2024-12-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_venda_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='xml_cfe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
