# Generated by Django 5.1.3 on 2024-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_venda_codigo_retorno_venda_mensagem_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='retorno_sat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
