# Generated by Django 5.1.3 on 2024-12-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_retorno_sat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='codigo_retorno',
            new_name='arquivoCFeBase64',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='mensagem_retorno',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='retorno_sat',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='sat_cfe',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='sat_gerado',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='xml_cfe',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='xml_gerado',
        ),
        migrations.AddField(
            model_name='venda',
            name='CPFCNPJValue',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='assinaturaQRCODE',
            field=models.CharField(blank=True, max_length=344, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cccc',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='chaveConsulta',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cod',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='eeeee',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='mensagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='mensagem_sefaz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='numeroSessao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='timeStamp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valorTotalCFe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
