# Generated by Django 5.1.3 on 2024-12-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_rename_codigo_retorno_venda_arquivocfebase64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='retornoSAT',
            field=models.TextField(blank=True, null=True),
        ),
    ]
